#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleList.Resource", IsApplication=true)]

namespace SimpleList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int left_m = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int right_m = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int top_m = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blank_avatar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int address_et = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int avatar_image = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int button_save = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int email_et = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int listView1 = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int phone_et = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int sort_button = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textView3 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int textView4 = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int user_name_text = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int UserInfo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int UserItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int SaveButtonText = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Sort = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int UserAddress = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int UserEmail = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int UserName = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int UserPhone = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
